# -*- coding: utf-8 -*-
"""Final_Glaucoma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TChym1qZfk3dNy4GnVpiwiYb90_BQJsV
"""

# -*- coding: utf-8 -*-
"""HACapsNet Training with Complete Research Paper Visualizations"""

# ---------------------- Imports ----------------------
import os, random, time
import numpy as np
import pandas as pd
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torchvision import models, transforms as T
from sklearn.metrics import (accuracy_score, f1_score, matthews_corrcoef,
                             roc_auc_score, confusion_matrix, classification_report,
                             precision_score, recall_score, roc_curve, precision_recall_curve, auc)
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import cv2

from google.colab import drive
drive.mount('/content/drive')

# ---------------------- CONFIG ----------------------
class CFG:
    raw_path    = "/content/drive/MyDrive/REFUGE2/train/images"
    masks_path  = "/content/drive/MyDrive/REFUGE2/train/mask"
    output_path = "/content/drive/MyDrive/REFUGE2"
    csv_path    = "/content/drive/MyDrive/REFUGE2/refuge_data.csv"

    batch_size = 8
    lr = 1e-4
    num_epochs = 50
    patience = 2
    num_workers = 4
    seed = 42
    device = 'cuda' if torch.cuda.is_available() else 'cpu'

    # Visualization output directory
    vis_path = "/content/drive/MyDrive/REFUGE2/visualizations1"
    os.makedirs(vis_path, exist_ok=True)

    print(f"Using device: {device}")

torch.manual_seed(CFG.seed)
np.random.seed(CFG.seed)
random.seed(CFG.seed)

# =====================================================
# Utility Functions
# =====================================================
def compute_dice_score(pred_mask, true_mask, threshold=0.5):
    """Compute Dice coefficient"""
    pred_binary = (pred_mask > threshold).float()
    true_binary = (true_mask > threshold).float()

    intersection = (pred_binary * true_binary).sum()
    dice = (2. * intersection) / (pred_binary.sum() + true_binary.sum() + 1e-8)
    return dice.item()

# =====================================================
# Dataset with In-Memory Caching
# =====================================================
class CachedGlaucomaDataset(Dataset):
    def __init__(self, csv_file, split='train', augment=False, use_cache=True):
        self.df = pd.read_csv(csv_file, encoding='latin1')
        self.df = self.df[self.df['split'] == split].reset_index(drop=True)
        self.augment = augment and split == 'train'
        self.img_size = 512
        self.use_cache = use_cache
        self.cache = {}

        if self.use_cache:
            print(f"\n{'='*70}")
            print(f"CACHING {split.upper()} DATASET IN MEMORY")
            print(f"{'='*70}")
            for idx in tqdm(range(len(self.df)), desc=f"Caching {split}"):
                row = self.df.iloc[idx]
                image = Image.open(row['image_path']).convert("RGB")
                mask = Image.open(row['mask_path']).convert("L")
                self.cache[idx] = {
                    'image': image.copy(),
                    'mask': mask.copy(),
                    'label': row['label']
                }
            print(f"✓ {len(self.cache)} images cached!\n")

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        if self.use_cache and idx in self.cache:
            image = self.cache[idx]['image'].copy()
            mask = self.cache[idx]['mask'].copy()
            label = torch.tensor(self.cache[idx]['label'], dtype=torch.long)
        else:
            row = self.df.iloc[idx]
            image = Image.open(row['image_path']).convert("RGB")
            mask = Image.open(row['mask_path']).convert("L")
            label = torch.tensor(row['label'], dtype=torch.long)

        # CLAHE preprocessing
        img_cv = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2LAB)
        l, a, b = cv2.split(img_cv)
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        l_clahe = clahe.apply(l)
        img_clahe = cv2.merge((l_clahe, a, b))
        image = Image.fromarray(cv2.cvtColor(img_clahe, cv2.COLOR_LAB2RGB))

        if self.augment and random.random() > 0.5:
            image = T.ColorJitter(brightness=0.2, contrast=0.2)(image)

        transform_img = T.Compose([
            T.Resize((self.img_size, self.img_size)),
            T.ToTensor(),
            T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ])
        transform_mask = T.Compose([
            T.Resize((self.img_size, self.img_size), interpolation=T.InterpolationMode.NEAREST),
            T.ToTensor()
        ])

        return transform_img(image), transform_mask(mask), label

# =====================================================
# Capsule Network Layers
# =====================================================
class PrimaryCaps(nn.Module):
    def __init__(self, input_channels, num_capsules=8, dim_capsule=16, kernel_size=3, stride=2):
        super().__init__()
        self.conv = nn.Conv2d(input_channels, num_capsules * dim_capsule,
                              kernel_size=kernel_size, stride=stride, padding=1)
        self.num_capsules = num_capsules
        self.dim_capsule = dim_capsule

    def squash(self, x, eps=1e-7):
        norm = torch.norm(x, dim=2, keepdim=True)
        scale = (norm ** 2) / (1 + norm ** 2)
        return scale * x / (norm + eps)

    def forward(self, x):
        B = x.size(0)
        u = self.conv(x)
        u = u.view(B, self.num_capsules, self.dim_capsule, -1)
        u = u.permute(0, 1, 3, 2).contiguous()
        u = u.view(B, -1, self.dim_capsule)
        return self.squash(u)

class DigitCaps(nn.Module):
    def __init__(self, dim_caps_in, num_caps_out=2, dim_caps_out=16, num_routing=3):
        super().__init__()
        self.num_caps_out = num_caps_out
        self.dim_caps_out = dim_caps_out
        self.num_routing = num_routing
        self.W = None

    def squash(self, x, eps=1e-7):
        norm = torch.norm(x, dim=-1, keepdim=True)
        scale = (norm ** 2) / (1 + norm ** 2)
        return scale * x / (norm + eps)

    def forward(self, x):
        B, num_caps_in, dim_caps_in = x.size()
        if self.W is None or self.W.size(1) != num_caps_in:
            self.W = nn.Parameter(0.01 * torch.randn(1, num_caps_in, self.num_caps_out,
                                                     self.dim_caps_out, dim_caps_in, device=x.device))
        x = x.unsqueeze(2).unsqueeze(4)
        u_hat = torch.matmul(self.W, x).squeeze(4)
        b_ij = torch.zeros(1, num_caps_in, self.num_caps_out, 1, device=x.device)

        for r in range(self.num_routing):
            c_ij = F.softmax(b_ij, dim=2)
            s_j = (c_ij * u_hat).sum(dim=1, keepdim=True)
            v_j = self.squash(s_j)
            if r < self.num_routing - 1:
                b_ij = b_ij + (u_hat * v_j).sum(dim=-1, keepdim=True)
        return v_j.squeeze(1)

# =====================================================
# HACapsNet Model
# =====================================================
class HACapsNet(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()
        backbone = models.resnet18(pretrained=True)
        self.encoder = nn.Sequential(*list(backbone.children())[:-2])
        self.feature_dim = 512

        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(self.feature_dim, 256, 2, stride=2),
            nn.ReLU(),
            nn.ConvTranspose2d(256, 128, 2, stride=2),
            nn.ReLU(),
            nn.ConvTranspose2d(128, 1, 1)
        )

        self.primary_caps = PrimaryCaps(input_channels=self.feature_dim,
                                        num_capsules=8, dim_capsule=16)
        self.dropout_caps = nn.Dropout(0.3)
        self.digit_caps = DigitCaps(dim_caps_in=16, num_caps_out=num_classes,
                                    dim_caps_out=16, num_routing=3)

    def forward(self, x):
        enc = self.encoder(x)
        seg = self.decoder(enc)

        primary_caps = self.primary_caps(enc)
        primary_caps = self.dropout_caps(primary_caps)
        digit_caps = self.digit_caps(primary_caps)
        cls = torch.norm(digit_caps, dim=-1)

        return seg, cls

# =====================================================
# Focal Loss
# =====================================================
class FocalLoss(nn.Module):
    def __init__(self, alpha=3.0, gamma=2.0):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none',
                                  weight=torch.tensor([1.0, self.alpha]).to(inputs.device))
        pt = torch.exp(-ce_loss)
        focal_loss = ((1 - pt) ** self.gamma) * ce_loss
        return focal_loss.mean()

# =====================================================
# Dataset Loading
# =====================================================
USE_CACHE = False

train_dataset = CachedGlaucomaDataset(CFG.csv_path, split='train', augment=True, use_cache=USE_CACHE)
val_dataset = CachedGlaucomaDataset(CFG.csv_path, split='val', augment=False, use_cache=USE_CACHE)

train_labels = [label.item() for _, _, label in train_dataset]
val_labels = [label.item() for _, _, label in val_dataset]

print("\n" + "="*60)
print("DATASET CLASS DISTRIBUTION")
print("="*60)
train_counts = np.bincount(train_labels)
val_counts = np.bincount(val_labels)
print(f"Train: Class 0={train_counts[0]}, Class 1={train_counts[1]}")
print(f"Val:   Class 0={val_counts[0]}, Class 1={val_counts[1]}")
print("="*60)

# Weighted sampler for class imbalance
class_counts = np.bincount(train_labels)
weights = 1.0 / torch.tensor(class_counts, dtype=torch.float)
sample_weights = [weights[label] for label in train_labels]
sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)

train_loader = DataLoader(train_dataset, batch_size=CFG.batch_size,
                          sampler=sampler, num_workers=CFG.num_workers)
val_loader = DataLoader(val_dataset, batch_size=CFG.batch_size,
                        shuffle=False, num_workers=CFG.num_workers)

# =====================================================
# Model Setup
# =====================================================
model = HACapsNet().to(CFG.device)
optimizer = optim.AdamW(model.parameters(), lr=CFG.lr, weight_decay=1e-3)
cls_criterion = FocalLoss(alpha=3.0, gamma=2.0)
seg_criterion = nn.BCEWithLogitsLoss()

# Initialize early stopping variables
best_loss = float('inf')
no_improve_epochs = 0

history = {
    'train_loss': [], 'train_acc': [], 'train_f1': [], 'train_dice': [],
    'train_mcc': [], 'train_precision': [], 'train_recall': [],
    'epoch_times': [], 'seg_loss': [], 'cls_loss': []
}

# =====================================================
# TRAINING LOOP
# =====================================================
print("\n" + "="*70)
print("STARTING TRAINING")
print("="*70)

for epoch in range(CFG.num_epochs):
    start_time = time.time()
    model.train()

    seg_loss_total, cls_loss_total = 0.0, 0.0
    preds_train, labels_train = [], []
    dice_scores_train = []

    for imgs, masks, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{CFG.num_epochs}"):
        imgs, masks, labels = imgs.to(CFG.device), masks.to(CFG.device), labels.to(CFG.device)

        optimizer.zero_grad()
        seg_out, cls_out = model(imgs)
        seg_out = F.interpolate(seg_out, size=masks.shape[2:], mode='bilinear', align_corners=False)

        seg_loss = seg_criterion(seg_out, masks)
        cls_loss = cls_criterion(cls_out, labels)
        loss = 0.5 * seg_loss + 2.0 * cls_loss

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        seg_loss_total += seg_loss.item()
        cls_loss_total += cls_loss.item()

        preds = torch.argmax(cls_out, dim=1).detach().cpu().numpy()
        preds_train.extend(preds)
        labels_train.extend(labels.detach().cpu().numpy())

        with torch.no_grad():
            for i in range(seg_out.size(0)):
                dice_scores_train.append(compute_dice_score(seg_out[i], masks[i]))

    # Compute metrics
    train_f1 = f1_score(labels_train, preds_train)
    train_acc = accuracy_score(labels_train, preds_train)
    train_mcc = matthews_corrcoef(labels_train, preds_train)
    train_precision = precision_score(labels_train, preds_train, zero_division=0)
    train_recall = recall_score(labels_train, preds_train, zero_division=0)
    train_dice = np.mean(dice_scores_train)
    train_seg_loss = seg_loss_total / len(train_loader)
    train_cls_loss = cls_loss_total / len(train_loader)
    train_loss = 0.5 * train_seg_loss + 2.0 * train_cls_loss
    epoch_time = time.time() - start_time

    # Store history
    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['train_f1'].append(train_f1)
    history['train_dice'].append(train_dice)
    history['train_mcc'].append(train_mcc)
    history['train_precision'].append(train_precision)
    history['train_recall'].append(train_recall)
    history['epoch_times'].append(epoch_time)
    history['seg_loss'].append(train_seg_loss)
    history['cls_loss'].append(train_cls_loss)

    # Print epoch summary
    print(f"\n{'='*70}")
    print(f"EPOCH {epoch+1}/{CFG.num_epochs}  (Time: {epoch_time:.2f}s)")
    print(f"{'='*70}")
    print(f"Seg Loss: {train_seg_loss:.4f} | Cls Loss: {train_cls_loss:.4f}")
    print(f"Total Loss: {train_loss:.4f}")
    print(f"Acc: {train_acc:.4f} | F1: {train_f1:.4f} | MCC: {train_mcc:.4f}")
    print(f"Precision: {train_precision:.4f} | Recall: {train_recall:.4f}")
    print(f"Dice: {train_dice:.4f}")
    print(f"Pred - Class 0: {sum(p == 0 for p in preds_train)}, Class 1: {sum(p == 1 for p in preds_train)}")
    print(f"True - Class 0: {sum(l == 0 for l in labels_train)}, Class 1: {sum(l == 1 for l in labels_train)}")

    # Early stopping
    if train_loss < best_loss:
        best_loss = train_loss
        no_improve_epochs = 0
        best_model_path = os.path.join(CFG.output_path, "best_model.pth")
        torch.save(model.state_dict(), best_model_path)
        print(f"✓ Best model saved!")
    else:
        no_improve_epochs += 1
        print(f"No improvement for {no_improve_epochs} epoch(s).")

        if no_improve_epochs >= CFG.patience:
            print(f"\n⏹ Early stopping triggered at epoch {epoch+1}")
            break

    torch.cuda.empty_cache()

# Save final model
final_model_path = os.path.join(CFG.output_path, "final_model.pth")
torch.save(model.state_dict(), final_model_path)
print(f"\n✓ Final model saved to: {final_model_path}")

print("\n" + "="*70)
print("TRAINING COMPLETE!")
print("="*70)
print(f"Total Training Time: {sum(history['epoch_times'])/60:.2f} minutes")
print(f"Average Epoch Time: {np.mean(history['epoch_times']):.2f} seconds")
print("="*70)

# =====================================================
# FINAL TEST EVALUATION ON VALIDATION DATA
# =====================================================
print("\n" + "="*70)
print("FINAL TEST EVALUATION ON VALIDATION DATA")
print("="*70)

model.load_state_dict(torch.load(os.path.join(CFG.output_path, "final_model.pth")))
model.eval()

all_preds, all_labels, all_probs = [], [], []
all_dice_scores = []
all_seg_outputs = []
all_seg_masks = []
all_images = []

with torch.no_grad():
    for imgs, masks, labels in tqdm(val_loader, desc="Testing"):
        imgs, masks, labels = imgs.to(CFG.device), masks.to(CFG.device), labels.to(CFG.device)
        seg_out, cls_out = model(imgs)
        seg_out = F.interpolate(seg_out, size=masks.shape[2:], mode='bilinear', align_corners=False)

        preds = torch.argmax(cls_out, dim=1).cpu().numpy()
        probs = F.softmax(cls_out, dim=1)[:, 1].cpu().numpy()

        all_preds.extend(preds)
        all_labels.extend(labels.cpu().numpy())
        all_probs.extend(probs)

        # Store for visualization
        all_images.append(imgs.cpu())
        all_seg_outputs.append(seg_out.cpu())
        all_seg_masks.append(masks.cpu())

        for i in range(seg_out.size(0)):
            all_dice_scores.append(compute_dice_score(seg_out[i], masks[i]))

# Calculate metrics
final_acc = accuracy_score(all_labels, all_preds)
final_f1 = f1_score(all_labels, all_preds)
final_mcc = matthews_corrcoef(all_labels, all_preds)
final_precision = precision_score(all_labels, all_preds, zero_division=0)
final_recall = recall_score(all_labels, all_preds, zero_division=0)
final_dice = np.mean(all_dice_scores)
roc_auc = roc_auc_score(all_labels, all_probs)

print("\n" + "="*70)
print("FINAL TEST RESULTS")
print("="*70)
print(f"Test Accuracy:   {final_acc:.4f}")
print(f"Test Precision:  {final_precision:.4f}")
print(f"Test Recall:     {final_recall:.4f}")
print(f"Test F1 Score:   {final_f1:.4f}")
print(f"Test MCC:        {final_mcc:.4f}")
print(f"Test Dice Score: {final_dice:.4f}")
print(f"Test AUC-ROC:    {roc_auc:.4f}")
print("="*70)

# Classification Report
labels_names = ['Normal', 'Glaucoma']
print("\n" + "="*70)
print("CLASSIFICATION REPORT")
print("="*70)
print(classification_report(all_labels, all_preds, target_names=labels_names))
print("="*70)

# Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)
print("\nConfusion Matrix:")
print(cm)
print(f"\nTest Predictions:")
print(f"  Predicted - Class 0: {sum(p == 0 for p in all_preds)}, Class 1: {sum(p == 1 for p in all_preds)}")
print(f"  True      - Class 0: {sum(l == 0 for l in all_labels)}, Class 1: {sum(l == 1 for l in all_labels)}")

# =====================================================
# VISUALIZATION FUNCTIONS
# =====================================================

def plot_training_curves():
    """Plot training loss, accuracy, F1, and Dice curves"""
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    fig.suptitle('Training Performance Curves', fontsize=16, fontweight='bold')

    epochs = range(1, len(history['train_loss']) + 1)

    # Total Loss
    axes[0, 0].plot(epochs, history['train_loss'], 'b-', linewidth=2, marker='o')
    axes[0, 0].set_title('Total Training Loss', fontweight='bold')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('Loss')
    axes[0, 0].grid(True, alpha=0.3)

    # Segmentation Loss
    axes[0, 1].plot(epochs, history['seg_loss'], 'g-', linewidth=2, marker='s')
    axes[0, 1].set_title('Segmentation Loss', fontweight='bold')
    axes[0, 1].set_xlabel('Epoch')
    axes[0, 1].set_ylabel('Loss')
    axes[0, 1].grid(True, alpha=0.3)

    # Classification Loss
    axes[0, 2].plot(epochs, history['cls_loss'], 'r-', linewidth=2, marker='^')
    axes[0, 2].set_title('Classification Loss', fontweight='bold')
    axes[0, 2].set_xlabel('Epoch')
    axes[0, 2].set_ylabel('Loss')
    axes[0, 2].grid(True, alpha=0.3)

    # Accuracy
    axes[1, 0].plot(epochs, history['train_acc'], 'purple', linewidth=2, marker='o')
    axes[1, 0].set_title('Training Accuracy', fontweight='bold')
    axes[1, 0].set_xlabel('Epoch')
    axes[1, 0].set_ylabel('Accuracy')
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].set_ylim([0, 1])

    # F1 Score
    axes[1, 1].plot(epochs, history['train_f1'], 'orange', linewidth=2, marker='s')
    axes[1, 1].set_title('F1 Score', fontweight='bold')
    axes[1, 1].set_xlabel('Epoch')
    axes[1, 1].set_ylabel('F1 Score')
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].set_ylim([0, 1])

    # Dice Score
    axes[1, 2].plot(epochs, history['train_dice'], 'cyan', linewidth=2, marker='^')
    axes[1, 2].set_title('Dice Score', fontweight='bold')
    axes[1, 2].set_xlabel('Epoch')
    axes[1, 2].set_ylabel('Dice Score')
    axes[1, 2].grid(True, alpha=0.3)
    axes[1, 2].set_ylim([0, 1])

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '01_training_curves.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 01_training_curves.png")

def plot_roc_curve():
    """Plot ROC curve"""
    fpr, tpr, thresholds = roc_curve(all_labels, all_probs)
    roc_auc_val = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='darkorange', lw=2,
             label=f'ROC curve (AUC = {roc_auc_val:.4f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Classifier')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate', fontsize=12)
    plt.ylabel('True Positive Rate', fontsize=12)
    plt.title('Receiver Operating Characteristic (ROC) Curve', fontsize=14, fontweight='bold')
    plt.legend(loc="lower right", fontsize=10)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '03_roc_curve.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 03_roc_curve.png")

def plot_precision_recall_curve():
    """Plot Precision-Recall curve"""
    precision, recall, thresholds = precision_recall_curve(all_labels, all_probs)
    pr_auc = auc(recall, precision)

    plt.figure(figsize=(8, 6))
    plt.plot(recall, precision, color='blue', lw=2,
             label=f'PR curve (AUC = {pr_auc:.4f})')
    plt.xlabel('Recall', fontsize=12)
    plt.ylabel('Precision', fontsize=12)
    plt.title('Precision-Recall Curve', fontsize=14, fontweight='bold')
    plt.legend(loc="lower left", fontsize=10)
    plt.grid(True, alpha=0.3)
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '04_precision_recall_curve.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 04_precision_recall_curve.png")

def plot_class_distribution():
    """Plot class distribution for train/val sets"""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Training set
    axes[0].bar(['Normal', 'Glaucoma'], train_counts, color=['#3498db', '#e74c3c'], alpha=0.8)
    axes[0].set_title('Training Set Distribution', fontweight='bold', fontsize=12)
    axes[0].set_ylabel('Count', fontsize=11)
    axes[0].grid(axis='y', alpha=0.3)
    for i, v in enumerate(train_counts):
        axes[0].text(i, v + 5, str(v), ha='center', fontweight='bold')

    # Validation set
    axes[1].bar(['Normal', 'Glaucoma'], val_counts, color=['#3498db', '#e74c3c'], alpha=0.8)
    axes[1].set_title('Validation Set Distribution', fontweight='bold', fontsize=12)
    axes[1].set_ylabel('Count', fontsize=11)
    axes[1].grid(axis='y', alpha=0.3)
    for i, v in enumerate(val_counts):
        axes[1].text(i, v + 5, str(v), ha='center', fontweight='bold')

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '05_class_distribution.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 05_class_distribution.png")

def plot_metrics_comparison():
    """Plot bar chart comparing all metrics"""
    metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'MCC', 'Dice', 'AUC-ROC']
    values = [final_acc, final_precision, final_recall, final_f1,
              (final_mcc + 1) / 2, final_dice, roc_auc]  # Normalize MCC to [0,1]

    plt.figure(figsize=(10, 6))
    colors = plt.cm.viridis(np.linspace(0, 0.9, len(metrics)))
    bars = plt.bar(metrics, values, color=colors, alpha=0.8)
    plt.title('Model Performance Metrics', fontsize=14, fontweight='bold')
    plt.ylabel('Score', fontsize=12)
    plt.ylim([0, 1.0])
    plt.grid(axis='y', alpha=0.3)
    plt.xticks(rotation=45, ha='right')

    # Add value labels on bars
    for bar, val in zip(bars, values):
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2., height,
                f'{val:.3f}', ha='center', va='bottom', fontweight='bold')

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '06_metrics_comparison.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 06_metrics_comparison.png")

def plot_segmentation_results(num_samples=8):
    """Plot qualitative segmentation results"""
    model.eval()

    # Get random samples
    indices = random.sample(range(len(val_dataset)), min(num_samples, len(val_dataset)))

    fig, axes = plt.subplots(num_samples, 3, figsize=(12, 4*num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    with torch.no_grad():
        for idx, sample_idx in enumerate(indices):
            img, mask, label = val_dataset[sample_idx]
            img_tensor = img.unsqueeze(0).to(CFG.device)
            mask_tensor = mask.unsqueeze(0).to(CFG.device)

            seg_out, cls_out = model(img_tensor)
            seg_out = F.interpolate(seg_out, size=mask.shape[1:], mode='bilinear', align_corners=False)
            pred_mask = torch.sigmoid(seg_out).squeeze().cpu().numpy()

            # Denormalize image
            img_np = img.cpu().numpy().transpose(1, 2, 0)
            img_np = img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
            img_np = np.clip(img_np, 0, 1)

            # Plot
            axes[idx, 0].imshow(img_np)
            axes[idx, 0].set_title(f'Original Image\nTrue: {labels_names[label.item()]}', fontweight='bold')
            axes[idx, 0].axis('off')

            axes[idx, 1].imshow(mask.squeeze().cpu().numpy(), cmap='gray')
            axes[idx, 1].set_title('Ground Truth Mask', fontweight='bold')
            axes[idx, 1].axis('off')

            axes[idx, 2].imshow(pred_mask, cmap='gray')
            dice = compute_dice_score(torch.tensor(pred_mask).unsqueeze(0), mask)
            axes[idx, 2].set_title(f'Predicted Mask\nDice: {dice:.3f}', fontweight='bold')
            axes[idx, 2].axis('off')

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '07_segmentation_results.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 07_segmentation_results.png")

def plot_segmentation_overlay(num_samples=6):
    """Plot segmentation masks overlaid on original images"""
    model.eval()

    indices = random.sample(range(len(val_dataset)), min(num_samples, len(val_dataset)))

    fig, axes = plt.subplots(2, num_samples//2, figsize=(15, 8))
    axes = axes.flatten()

    with torch.no_grad():
        for idx, sample_idx in enumerate(indices):
            img, mask, label = val_dataset[sample_idx]
            img_tensor = img.unsqueeze(0).to(CFG.device)

            seg_out, cls_out = model(img_tensor)
            seg_out = F.interpolate(seg_out, size=mask.shape[1:], mode='bilinear', align_corners=False)
            pred_mask = torch.sigmoid(seg_out).squeeze().cpu().numpy()

            # Denormalize image
            img_np = img.cpu().numpy().transpose(1, 2, 0)
            img_np = img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
            img_np = np.clip(img_np, 0, 1)

            # Create overlay
            overlay = img_np.copy()
            mask_rgb = np.zeros_like(overlay)
            mask_rgb[:, :, 0] = pred_mask > 0.5  # Red channel for prediction
            overlay = cv2.addWeighted(overlay, 0.7, mask_rgb, 0.3, 0)

            axes[idx].imshow(overlay)
            axes[idx].set_title(f'{labels_names[label.item()]}', fontweight='bold')
            axes[idx].axis('off')

    plt.suptitle('Predicted Segmentation Overlays (Red)', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '08_segmentation_overlay.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 08_segmentation_overlay.png")

def generate_gradcam(img_tensor, model, target_layer):
    """Generate Grad-CAM visualization"""
    model.eval()

    # Forward pass
    activations = []
    gradients = []

    def forward_hook(module, input, output):
        activations.append(output)

    def backward_hook(module, grad_input, grad_output):
        gradients.append(grad_output[0])

    handle_forward = target_layer.register_forward_hook(forward_hook)
    handle_backward = target_layer.register_full_backward_hook(backward_hook)

    seg_out, cls_out = model(img_tensor)
    pred_class = torch.argmax(cls_out, dim=1)

    model.zero_grad()
    cls_out[0, pred_class].backward()

    activation = activations[0].detach()
    gradient = gradients[0].detach()

    weights = torch.mean(gradient, dim=[2, 3], keepdim=True)
    cam = torch.sum(weights * activation, dim=1, keepdim=True)
    cam = F.relu(cam)
    cam = F.interpolate(cam, size=img_tensor.shape[2:], mode='bilinear', align_corners=False)
    cam = cam.squeeze().cpu().numpy()
    cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

    handle_forward.remove()
    handle_backward.remove()

    return cam

def plot_gradcam_visualizations(num_samples=6):
    """Plot Grad-CAM attention maps"""
    model.eval()

    indices = random.sample(range(len(val_dataset)), min(num_samples, len(val_dataset)))

    fig, axes = plt.subplots(num_samples, 3, figsize=(12, 4*num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    target_layer = model.encoder[-1]  # Last layer of encoder

    for idx, sample_idx in enumerate(indices):
        img, mask, label = val_dataset[sample_idx]
        img_tensor = img.unsqueeze(0).to(CFG.device)
        img_tensor.requires_grad = True

        # Generate Grad-CAM
        cam = generate_gradcam(img_tensor, model, target_layer)

        # Denormalize image
        img_np = img.cpu().numpy().transpose(1, 2, 0)
        img_np = img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
        img_np = np.clip(img_np, 0, 1)

        # Plot
        axes[idx, 0].imshow(img_np)
        axes[idx, 0].set_title(f'Original\n{labels_names[label.item()]}', fontweight='bold')
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(cam, cmap='jet')
        axes[idx, 1].set_title('Grad-CAM Heatmap', fontweight='bold')
        axes[idx, 1].axis('off')

        # Overlay
        heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
        heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB) / 255.0
        overlay = heatmap * 0.4 + img_np * 0.6
        axes[idx, 2].imshow(overlay)
        axes[idx, 2].set_title('Grad-CAM Overlay', fontweight='bold')
        axes[idx, 2].axis('off')

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '09_gradcam_visualization.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 09_gradcam_visualization.png")

def generate_saliency_map(img_tensor, model):
    """Generate saliency map"""
    model.eval()
    img_tensor.requires_grad = True

    seg_out, cls_out = model(img_tensor)
    pred_class = torch.argmax(cls_out, dim=1)

    model.zero_grad()
    cls_out[0, pred_class].backward()

    saliency = img_tensor.grad.data.abs()
    saliency = torch.max(saliency, dim=1)[0]
    saliency = saliency.squeeze().cpu().numpy()
    saliency = (saliency - saliency.min()) / (saliency.max() - saliency.min() + 1e-8)

    return saliency

def plot_saliency_maps(num_samples=6):
    """Plot saliency maps"""
    model.eval()

    indices = random.sample(range(len(val_dataset)), min(num_samples, len(val_dataset)))

    fig, axes = plt.subplots(num_samples, 3, figsize=(12, 4*num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    for idx, sample_idx in enumerate(indices):
        img, mask, label = val_dataset[sample_idx]
        img_tensor = img.unsqueeze(0).to(CFG.device)
        img_tensor.requires_grad = True

        # Generate saliency map
        saliency = generate_saliency_map(img_tensor, model)

        # Denormalize image
        img_np = img.cpu().numpy().transpose(1, 2, 0)
        img_np = img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
        img_np = np.clip(img_np, 0, 1)

        # Plot
        axes[idx, 0].imshow(img_np)
        axes[idx, 0].set_title(f'Original\n{labels_names[label.item()]}', fontweight='bold')
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(saliency, cmap='hot')
        axes[idx, 1].set_title('Saliency Map', fontweight='bold')
        axes[idx, 1].axis('off')

        # Overlay
        saliency_rgb = plt.cm.hot(saliency)[:, :, :3]
        overlay = saliency_rgb * 0.4 + img_np * 0.6
        axes[idx, 2].imshow(overlay)
        axes[idx, 2].set_title('Saliency Overlay', fontweight='bold')
        axes[idx, 2].axis('off')

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '10_saliency_maps.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 10_saliency_maps.png")

def plot_error_analysis():
    """Plot error analysis - false positives and false negatives"""
    model.eval()

    # Find misclassified samples
    fp_indices = []  # False positives
    fn_indices = []  # False negatives

    with torch.no_grad():
        for idx in range(len(val_dataset)):
            img, mask, label = val_dataset[idx]
            img_tensor = img.unsqueeze(0).to(CFG.device)

            seg_out, cls_out = model(img_tensor)
            pred = torch.argmax(cls_out, dim=1).item()
            true = label.item()

            if pred == 1 and true == 0:  # False positive
                fp_indices.append(idx)
            elif pred == 0 and true == 1:  # False negative
                fn_indices.append(idx)

    num_fp = min(3, len(fp_indices))
    num_fn = min(3, len(fn_indices))

    if num_fp == 0 and num_fn == 0:
        print("✓ No misclassifications found!")
        return

    fig, axes = plt.subplots(2, 3, figsize=(15, 10))

    # Plot false positives
    for i in range(3):
        if i < num_fp:
            idx = fp_indices[i]
            img, mask, label = val_dataset[idx]
            img_np = img.cpu().numpy().transpose(1, 2, 0)
            img_np = img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
            img_np = np.clip(img_np, 0, 1)

            axes[0, i].imshow(img_np)
            axes[0, i].set_title(f'False Positive {i+1}\nTrue: Normal, Pred: Glaucoma',
                                fontweight='bold', color='red')
            axes[0, i].axis('off')
        else:
            axes[0, i].axis('off')

    # Plot false negatives
    for i in range(3):
        if i < num_fn:
            idx = fn_indices[i]
            img, mask, label = val_dataset[idx]
            img_np = img.cpu().numpy().transpose(1, 2, 0)
            img_np = img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
            img_np = np.clip(img_np, 0, 1)

            axes[1, i].imshow(img_np)
            axes[1, i].set_title(f'False Negative {i+1}\nTrue: Glaucoma, Pred: Normal',
                                fontweight='bold', color='red')
            axes[1, i].axis('off')
        else:
            axes[1, i].axis('off')

    plt.suptitle('Error Analysis: Misclassified Samples', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '11_error_analysis.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 11_error_analysis.png")

def plot_capsule_activations(num_samples=4):
    """Visualize capsule activations"""
    model.eval()

    indices = random.sample(range(len(val_dataset)), min(num_samples, len(val_dataset)))

    fig, axes = plt.subplots(num_samples, 3, figsize=(12, 4*num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    with torch.no_grad():
        for idx, sample_idx in enumerate(indices):
            img, mask, label = val_dataset[sample_idx]
            img_tensor = img.unsqueeze(0).to(CFG.device)

            # Get intermediate activations
            enc = model.encoder(img_tensor)
            primary_caps = model.primary_caps(enc)
            digit_caps = model.digit_caps(primary_caps)

            # Denormalize image
            img_np = img.cpu().numpy().transpose(1, 2, 0)
            img_np = img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
            img_np = np.clip(img_np, 0, 1)

            # Plot original image
            axes[idx, 0].imshow(img_np)
            axes[idx, 0].set_title(f'{labels_names[label.item()]}', fontweight='bold')
            axes[idx, 0].axis('off')

            # Plot capsule norms
            caps_norms = torch.norm(digit_caps, dim=-1).squeeze().cpu().numpy()
            axes[idx, 1].bar(['Normal', 'Glaucoma'], caps_norms, color=['#3498db', '#e74c3c'])
            axes[idx, 1].set_title('Capsule Activations', fontweight='bold')
            axes[idx, 1].set_ylabel('Norm')
            axes[idx, 1].grid(axis='y', alpha=0.3)

            # Visualize primary capsule activations
            primary_activations = primary_caps[0].cpu().numpy()
            primary_vis = np.mean(np.abs(primary_activations), axis=1).reshape(8, -1)
            im = axes[idx, 2].imshow(primary_vis, cmap='viridis', aspect='auto')
            axes[idx, 2].set_title('Primary Capsules', fontweight='bold')
            axes[idx, 2].set_xlabel('Spatial Position')
            axes[idx, 2].set_ylabel('Capsule')
            plt.colorbar(im, ax=axes[idx, 2], fraction=0.046)

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '12_capsule_activations.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 12_capsule_activations.png")

def plot_dice_score_distribution():
    """Plot distribution of Dice scores"""
    dice_per_class = {0: [], 1: []}

    model.eval()
    with torch.no_grad():
        for idx in range(len(val_dataset)):
            img, mask, label = val_dataset[idx]
            img_tensor = img.unsqueeze(0).to(CFG.device)
            mask_tensor = mask.unsqueeze(0).to(CFG.device)

            seg_out, _ = model(img_tensor)
            seg_out = F.interpolate(seg_out, size=mask.shape[1:], mode='bilinear', align_corners=False)

            dice = compute_dice_score(seg_out[0], mask_tensor[0])
            dice_per_class[label.item()].append(dice)

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Box plot
    data_to_plot = [dice_per_class[0], dice_per_class[1]]
    bp = axes[0].boxplot(data_to_plot, labels=['Normal', 'Glaucoma'], patch_artist=True)
    for patch, color in zip(bp['boxes'], ['#3498db', '#e74c3c']):
        patch.set_facecolor(color)
        patch.set_alpha(0.7)
    axes[0].set_title('Dice Score Distribution by Class', fontweight='bold')
    axes[0].set_ylabel('Dice Score')
    axes[0].grid(axis='y', alpha=0.3)

    # Histogram
    axes[1].hist(dice_per_class[0], bins=20, alpha=0.5, label='Normal', color='#3498db')
    axes[1].hist(dice_per_class[1], bins=20, alpha=0.5, label='Glaucoma', color='#e74c3c')
    axes[1].set_title('Dice Score Histogram', fontweight='bold')
    axes[1].set_xlabel('Dice Score')
    axes[1].set_ylabel('Frequency')
    axes[1].legend()
    axes[1].grid(axis='y', alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '13_dice_distribution.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 13_dice_distribution.png")

def plot_feature_maps(num_samples=2):
    """Visualize intermediate feature maps"""
    model.eval()

    indices = random.sample(range(len(val_dataset)), min(num_samples, len(val_dataset)))

    for sample_num, sample_idx in enumerate(indices):
        img, mask, label = val_dataset[sample_idx]
        img_tensor = img.unsqueeze(0).to(CFG.device)

        # Get feature maps from encoder
        feature_maps = []
        x = img_tensor
        for i, layer in enumerate(model.encoder):
            x = layer(x)
            if isinstance(layer, nn.Conv2d) or isinstance(layer, nn.Sequential):
                feature_maps.append(x)

        # Plot first 16 channels of last conv layer
        last_features = feature_maps[-1][0].detach().cpu().numpy()[:16]

        fig, axes = plt.subplots(4, 4, figsize=(12, 12))
        axes = axes.flatten()

        for idx, (ax, feature) in enumerate(zip(axes, last_features)):
            ax.imshow(feature, cmap='viridis')
            ax.set_title(f'Channel {idx+1}', fontsize=9)
            ax.axis('off')

        # Denormalize image for reference
        img_np = img.cpu().numpy().transpose(1, 2, 0)
        img_np = img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
        img_np = np.clip(img_np, 0, 1)

        plt.suptitle(f'Feature Maps - {labels_names[label.item()]}', fontsize=14, fontweight='bold')
        plt.tight_layout()
        plt.savefig(os.path.join(CFG.vis_path, f'14_feature_maps_sample_{sample_num+1}.png'),
                   dpi=300, bbox_inches='tight')
        plt.close()

    print(f"✓ Saved: 14_feature_maps_sample_*.png")

def plot_performance_metrics_table():
    """Create a comprehensive metrics table"""
    metrics_data = {
        'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'MCC', 'Dice Score', 'AUC-ROC'],
        'Value': [final_acc, final_precision, final_recall, final_f1, final_mcc, final_dice, roc_auc]
    }

    df_metrics = pd.DataFrame(metrics_data)

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.axis('tight')
    ax.axis('off')

    table = ax.table(cellText=df_metrics.values,
                    colLabels=df_metrics.columns,
                    cellLoc='center',
                    loc='center',
                    colWidths=[0.5, 0.3])

    table.auto_set_font_size(False)
    table.set_fontsize(11)
    table.scale(1, 2)

    # Style header
    for i in range(len(df_metrics.columns)):
        table[(0, i)].set_facecolor('#4CAF50')
        table[(0, i)].set_text_props(weight='bold', color='white')

    # Style rows
    for i in range(1, len(df_metrics) + 1):
        for j in range(len(df_metrics.columns)):
            if i % 2 == 0:
                table[(i, j)].set_facecolor('#f0f0f0')
            if j == 1:  # Value column
                table[(i, j)].set_text_props(weight='bold')

    plt.title('Model Performance Metrics Summary', fontsize=14, fontweight='bold', pad=20)
    plt.savefig(os.path.join(CFG.vis_path, '15_metrics_table.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 15_metrics_table.png")

def plot_training_time_analysis():
    """Plot training time analysis"""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    epochs = range(1, len(history['epoch_times']) + 1)

    # Epoch times
    axes[0].plot(epochs, history['epoch_times'], 'o-', color='purple', linewidth=2)
    axes[0].set_title('Training Time per Epoch', fontweight='bold')
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Time (seconds)')
    axes[0].grid(True, alpha=0.3)
    axes[0].axhline(y=np.mean(history['epoch_times']), color='r', linestyle='--',
                   label=f'Mean: {np.mean(history["epoch_times"]):.2f}s')
    axes[0].legend()

    # Cumulative time
    cumulative_time = np.cumsum(history['epoch_times']) / 60  # Convert to minutes
    axes[1].plot(epochs, cumulative_time, 'o-', color='green', linewidth=2)
    axes[1].set_title('Cumulative Training Time', fontweight='bold')
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Time (minutes)')
    axes[1].grid(True, alpha=0.3)
    axes[1].fill_between(epochs, cumulative_time, alpha=0.3, color='green')

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '16_training_time_analysis.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 16_training_time_analysis.png")

def plot_all_metrics_progression():
    """Plot all metrics progression over epochs"""
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    epochs = range(1, len(history['train_acc']) + 1)

    # Accuracy & F1
    axes[0, 0].plot(epochs, history['train_acc'], 'b-', label='Accuracy', linewidth=2, marker='o')
    axes[0, 0].plot(epochs, history['train_f1'], 'r-', label='F1-Score', linewidth=2, marker='s')
    axes[0, 0].set_title('Accuracy & F1-Score Progression', fontweight='bold')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('Score')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].set_ylim([0, 1])

    # Precision & Recall
    axes[0, 1].plot(epochs, history['train_precision'], 'g-', label='Precision', linewidth=2, marker='o')
    axes[0, 1].plot(epochs, history['train_recall'], 'purple', label='Recall', linewidth=2, marker='s')
    axes[0, 1].set_title('Precision & Recall Progression', fontweight='bold')
    axes[0, 1].set_xlabel('Epoch')
    axes[0, 1].set_ylabel('Score')
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].set_ylim([0, 1])

    # MCC & Dice
    axes[1, 0].plot(epochs, history['train_mcc'], 'orange', label='MCC', linewidth=2, marker='o')
    axes[1, 0].plot(epochs, history['train_dice'], 'cyan', label='Dice Score', linewidth=2, marker='s')
    axes[1, 0].set_title('MCC & Dice Score Progression', fontweight='bold')
    axes[1, 0].set_xlabel('Epoch')
    axes[1, 0].set_ylabel('Score')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)

    # Combined Loss
    axes[1, 1].plot(epochs, history['train_loss'], 'b-', label='Total Loss', linewidth=2, marker='o')
    axes[1, 1].plot(epochs, history['seg_loss'], 'g-', label='Seg Loss', linewidth=2, marker='s')
    axes[1, 1].plot(epochs, history['cls_loss'], 'r-', label='Cls Loss', linewidth=2, marker='^')
    axes[1, 1].set_title('Loss Components Progression', fontweight='bold')
    axes[1, 1].set_xlabel('Epoch')
    axes[1, 1].set_ylabel('Loss')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '17_all_metrics_progression.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 17_all_metrics_progression.png")

# =====================================================
# GENERATE ALL VISUALIZATIONS
# =====================================================
print("\n" + "="*70)
print("GENERATING RESEARCH PAPER VISUALIZATIONS")
print("="*70)

# 1. Training curves
print("\n[1/17] Generating training curves...")
plot_training_curves()

# 2. Confusion matrix
print("[2/17] Generating confusion matrix...")
def plot_confusion_matrix():
    """Plot confusion matrix"""
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
                xticklabels=labels_names, yticklabels=labels_names)
    plt.title('Confusion Matrix', fontsize=14, fontweight='bold')
    plt.xlabel('Predicted Label', fontsize=12)
    plt.ylabel('True Label', fontsize=12)
    plt.tight_layout()
    plt.savefig(os.path.join(CFG.vis_path, '02_confusion_matrix.png'), dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Saved: 02_confusion_matrix.png")

plot_confusion_matrix()

# 3. ROC curve
print("[3/17] Generating ROC curve...")
plot_roc_curve()

# 4. Precision-Recall curve
print("[4/17] Generating Precision-Recall curve...")
plot_precision_recall_curve()

# 5. Class distribution
print("[5/17] Generating class distribution...")
plot_class_distribution()

# 6. Metrics comparison
print("[6/17] Generating metrics comparison...")
plot_metrics_comparison()

# 7. Segmentation results
print("[7/17] Generating segmentation results...")
plot_segmentation_results(num_samples=8)

# 8. Segmentation overlay
print("[8/17] Generating segmentation overlays...")
plot_segmentation_overlay(num_samples=6)

# 9. Grad-CAM
print("[9/17] Generating Grad-CAM visualizations...")
plot_gradcam_visualizations(num_samples=6)

# 10. Saliency maps
print("[10/17] Generating saliency maps...")
plot_saliency_maps(num_samples=6)

# 11. Error analysis
print("[11/17] Generating error analysis...")
plot_error_analysis()

# 12. Capsule activations
print("[12/17] Generating capsule activations...")
plot_capsule_activations(num_samples=4)

# 13. Dice distribution
print("[13/17] Generating Dice score distribution...")
plot_dice_score_distribution()

# 14. Feature maps
print("[14/17] Generating feature maps...")
plot_feature_maps(num_samples=2)

# 15. Metrics table
print("[15/17] Generating metrics table...")
plot_performance_metrics_table()

# 16. Training time analysis
print("[16/17] Generating training time analysis...")
plot_training_time_analysis()

# 17. All metrics progression
print("[17/17] Generating all metrics progression...")
plot_all_metrics_progression()

print("\n" + "="*70)
print("ALL VISUALIZATIONS GENERATED SUCCESSFULLY!")
print("="*70)
print(f"Visualizations saved to: {CFG.vis_path}")
print("\nGenerated files:")
print("  01_training_curves.png")
print("  02_confusion_matrix.png")
print("  03_roc_curve.png")
print("  04_precision_recall_curve.png")
print("  05_class_distribution.png")
print("  06_metrics_comparison.png")
print("  07_segmentation_results.png")
print("  08_segmentation_overlay.png")
print("  09_gradcam_visualization.png")
print("  10_saliency_maps.png")
print("  11_error_analysis.png")
print("  12_capsule_activations.png")
print("  13_dice_distribution.png")
print("  14_feature_maps_sample_*.png")
print("  15_metrics_table.png")
print("  16_training_time_analysis.png")
print("  17_all_metrics_progression.png")
print("="*70)

# =====================================================
# SAVE METRICS TO CSV
# =====================================================
results_df = pd.DataFrame({
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'MCC', 'Dice Score', 'AUC-ROC'],
    'Value': [final_acc, final_precision, final_recall, final_f1, final_mcc, final_dice, roc_auc]
})
results_df.to_csv(os.path.join(CFG.vis_path, 'test_metrics.csv'), index=False)
print("\n✓ Test metrics saved to: test_metrics.csv")

# Save training history
history_df = pd.DataFrame(history)
history_df.to_csv(os.path.join(CFG.vis_path, 'training_history.csv'), index=False)
print("✓ Training history saved to: training_history.csv")

print("\n" + "="*70)
print("COMPLETE WORKFLOW FINISHED!")
print("="*70)













